version: '3'
services:
  web:
    build: web
    depends_on:
      - db
    expose:
      - "80"
    links:
      - db
    volumes:
      - ./code/sqli-labs:/var/www/html
    ports:
      - "31334:80"
  db:
    image: mysql:5.7
    expose:
      - "3306"
    ports:
      - "8989:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
